### ISSUE TITLE
"This request requires user authentication."

### ISSUE THREAD

**Issue by sorentorp** [JMPerez/spotify-web-api-token#1]
Hi
Just want to say, that I am a big fan of your little project - nice and tight!

I'm trying to make some searches (works) and add the spotify URIs to a playlist on Spotify (does not work).

I get "This request requires user authentication." back from Spotify.

I suspect this is because the token that spotify-web-api-token requests, doesn't allow for editing playlists. Is that possible in some way, with this project?

**Comment by JMPerez** [comment]
Hi @sorentorp!

Thank you so much for your nice words. It really encourages me mainitaining these projects.

What is happenning what your request is that to add spotify URIs to a playlist you need permission from the playlist owner. This is done through using a Spotify login form that is shown as part of the [authorization process](https://developer.spotify.com/documentation/general/guides/authorization-guide/) using the Implicit Grant or Authorization Code flows. When implementing one of those flows you will also need to provide the right scope to perform the operation, which is `playlist-modify-public` or `playlist-modify-private` according [to the documentation of the endpoint](https://developer.spotify.com/documentation/web-api/reference/playlists/add-tracks-to-playlist/).

This library only implements the Client Credentials flow, and as such can't be used for your specific use case.

I recommend you to have a look at the authorization guide to get a better understanding of what's needed. If you plan to use node, you would like to know that there is [a nodejs wrapper for the Spotify Web API](https://github.com/thelinmichael/spotify-web-api-node) that includes handy methods for the authorization process.

**Comment by sorentorp** [comment]
Thank you for your response. I'm using Node Red, where your project made it very easy to implement.

I'm not sure that the nodejs wrapper is just as easy - I'm no code-ninja ;-)
